name: speed_and_success
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.1
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  connectivity: ^3.0.6
  http: ^0.13.0
  webview_flutter: ^3.0.4
  flutter_html: ^3.0.0-alpha.5
  unique_identifier: ^0.2.2
  device_info_plus: ^4.0.0
  flutter_local_notifications: ^9.7.0
  percent_indicator: ^4.2.2
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.2
  workmanager: ^0.5.0
  wakelock: ^0.6.2
  flutter_youtube_view: ^2.0.0
  flutter_inappwebview: ^5.3.2
  audio_video_progress_bar: ^0.10.0
  flutter_secure_storage: ^5.0.2
  video_player: ^2.1.15
  flutter_cache_manager:
  vimeo_player_flutter: ^0.0.3+1
  chewie: ^1.3.4
  better_player: ^0.0.73
  upgrader: ^4.4.0
  package_info_plus: ^1.4.0
  zoom_widget: ^0.2.1

  #device_information: ^0.0.4
  #permission_handler: ^9.2.0


  #flutter_math_fork: ^0.5.0
#  mac_address:
#  firebase_messaging: ^11.2.6 #null-safety
#  firebase_messaging: ^6.0.16
#  firebase_installations: ^16.3.6
#  youtube_player_flutter: ^8.0.0
#  share: ^2.0.4
#  validators: ^3.0.0
#  device_info: ^2.0.2
#  visibility_detector: ^0.2.0
#  package_info: ^2.0.2
#  permission_handler: ^8.1.4+2
#  youtube_player_iframe: ^2.2.2
#  photo_view: ^0.12.0
#  path: ^1.8.0
#  in_app_update: ^2.0.0
#  flutter_youtube_vimeo: ^0.0.1
#  flutter_svg: ^0.22.0
#  cupertino_icons: ^1.0.3
#  datetime_picker_formfield: ^2.0.0
#  firebase_core: ^1.6.0
#  flick_video_player: ^0.3.1
#  intl: ^0.17.0
#  get_it: ^7.2.0

  #  printing: ^5.2.1
#  asset_webview: ^0.0.4
#  url_launcher: ^6.0.4
#  flutter_windowmanager: ^0.1.0
#  secure_application: ^3.7.3
#  onesignal_flutter: ^3.2.3
  #  firebase_messaging: ^10.0.0 #null-safety
  #  cloud_firestore: ^2.5.1
  #  firebase_storage: ^8.1.0 #null-safety
  #  firebase_auth: ^1.2.0 #null-safety
  #  firebase_analytics: ^8.1.0 #null-safety
  #  provider: ^5.0.0
  #  path_provider: ^2.0.2
  #  get: ^4.3.8
  #  flutter_cache_manager: ^3.0.2
  #  popup_menu: ^1.0.5

  #  sqflite: ^2.0.0+4
  #  image_picker: ^0.7.5+2 #null-safety

#  dependency_validator:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.4

#dependency_overrides:
#  flutter_math_fork: ^0.5.0
#  provider: ^6.0.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/speed_and_success2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/speed_and_success2.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/speed_and_success.png
  color_dark: "#ffce06"
  image_dark: assets/icons/speed_and_success.png
  android: true
  ios: true
  web: true
  fullscreen: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/speed_and_success.png
    - assets/images/background8.jpg
    - assets/sounds/box_down.mp3
    - assets/sounds/box_up.mp3
    - assets/sounds/icon_choose.mp3
    - assets/sounds/icon_focus.mp3
    - assets/sounds/short_press_like.mp3
    - assets/sounds/slow_spring_board.mp3
    - assets/images/
    - assets/icons/
    - assets/sounds/
    #- assets/icons/comicerLogos/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
